language: node_js
node_js: stable

sudo: false

install: true

os:
  - linux

before_script:
  - npm install
  - npm install -g coveralls nyc

script:
  - npm run test && npm run lint

after_success:
  - nyc report --reporter=text-lcov | coveralls